# Generated by Django 6.0.3 on 2026-04-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_coupon_customerrisk_order_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
