# Generated by Django 6.0.2 on 2026-02-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_description_product_is_weight_based_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_weight_based',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_per_kg',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
