# Generated by Django 6.0.3 on 2026-04-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_order_rider_latitude_order_rider_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
    ]
