# Generated by Django 6.0.2 on 2026-02-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_order_accepted_at_order_assigned_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('REQUEST_SUBMITTED', 'Request Submitted'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('PICKED_UP', 'Picked Up'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='REQUEST_SUBMITTED', max_length=20),
        ),
    ]
