# Generated by Django 6.0.3 on 2026-05-07 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_orderitem_discount_amount_orderitem_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.bundle'),
        ),
    ]
