# Generated by Django 6.0.2 on 2026-03-05 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_bundle_bundleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bundle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.product'),
        ),
    ]
