# Generated by Django 6.0.3 on 2026-05-08 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_banner_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.bundle'),
        ),
    ]
