# Generated by Django 6.0.2 on 2026-03-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_order_delivery_otp_order_delivery_otp_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='items_snapshot',
            field=models.JSONField(default=dict),
        ),
    ]
