# Generated by Django 6.0.3 on 2026-05-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='cart_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
