# Generated by Django 6.0.3 on 2026-05-11 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_pendingorder_cart_data_pendingorder_is_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponusage',
            old_name='used_at',
            new_name='created_at',
        ),
    ]
