# Generated by Django 6.0.2 on 2026-03-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_customerrisk'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='is_payment_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='otp_expiry',
            field=models.DateTimeField(),
        ),
    ]
