# Generated by Django 6.0.3 on 2026-05-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_rename_used_at_couponusage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='is_payment_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
