# Generated by Django 6.0.3 on 2026-05-11 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_pendingorder_is_payment_processing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='created_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.order'),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
