# Generated by Django 6.0.2 on 2026-03-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_pendingorder_coupon_code_pendingorder_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upi_only',
            field=models.BooleanField(default=False, help_text='If enabled, this product allows only UPI payment'),
        ),
    ]
