# Generated by Django 6.0.2 on 2026-03-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_order_delivery_distance_order_delivery_payout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Platform commission percentage', max_digits=5),
        ),
    ]
