# Generated by Django 6.0.3 on 2026-05-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_checkoutlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutlead',
            name='last_cart_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='checkoutlead',
            name='last_payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checkoutlead',
            name='last_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.store'),
        ),
    ]
