# Generated by Django 6.0.3 on 2026-05-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_checkoutlead_last_cart_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
