# Generated by Django 6.0.2 on 2026-03-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_store_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='owner',
        ),
    ]
