# Generated by Django 6.0.3 on 2026-03-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_alter_bundle_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='resend_count',
            field=models.IntegerField(default=0),
        ),
    ]
