# Generated by Django 6.0.3 on 2026-05-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_offerslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide_afternoon',
            field=models.BooleanField(default=False, verbose_name='Hide in Afternoon (1PM-5PM)'),
        ),
        migrations.AddField(
            model_name='product',
            name='hide_evening',
            field=models.BooleanField(default=False, verbose_name='Hide in Evening (5PM-9PM)'),
        ),
        migrations.AddField(
            model_name='product',
            name='hide_morning',
            field=models.BooleanField(default=False, verbose_name='Hide in Morning (10AM-1PM)'),
        ),
    ]
