# Generated by Django 6.0.3 on 2026-03-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_pendingorder_resend_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='phone',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='deliverypartnerprofile',
            name='phone',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_partner_phone',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('REQUEST_SUBMITTED', 'Request Submitted'), ('ACCEPTED', 'Accepted'), ('PICKED_UP', 'Picked Up'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUEST_SUBMITTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='phone',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
