# Generated by Django 6.0.3 on 2026-05-29 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_product_hide_afternoon_product_hide_evening_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hide_afternoon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hide_evening',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hide_morning',
        ),
    ]
