# Generated by Django 6.0.3 on 2026-06-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_remove_product_hide_afternoon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unavailable_afternoon',
            field=models.BooleanField(default=False, help_text='Hide product from 1 PM - 5 PM'),
        ),
        migrations.AddField(
            model_name='product',
            name='unavailable_evening',
            field=models.BooleanField(default=False, help_text='Hide product from 5 PM - 9 PM'),
        ),
        migrations.AddField(
            model_name='product',
            name='unavailable_morning',
            field=models.BooleanField(default=False, help_text='Hide product from 10 AM - 1 PM'),
        ),
    ]
