# Generated by Django 6.0.3 on 2026-04-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_alter_bundle_created_at_alter_coupon_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upi_only',
            field=models.BooleanField(default=False),
        ),
    ]
