# Generated by Django 6.0.3 on 2026-04-10 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_alter_product_upi_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upi_only',
            field=models.BooleanField(default=False, help_text='If enabled, this product allows only UPI payment'),
        ),
        migrations.CreateModel(
            name='StoreHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='marketplace.store')),
            ],
        ),
    ]
