# Generated by Django 6.0.3 on 2026-06-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_product_unavailable_afternoon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured Store'),
        ),
    ]
