# Generated by Django 6.0.3 on 2026-04-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_alter_product_upi_only_storeholiday_storetiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
