# Generated by Django 6.0.3 on 2026-06-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_store_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='featured_priority',
            field=models.IntegerField(default=0),
        ),
    ]
