# Generated by Django 6.0.3 on 2026-04-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_store_close_time_store_open_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='store',
            name='open_time',
        ),
    ]
