# Generated by Django 6.0.3 on 2026-07-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_store_featured_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
