# Generated by Django 6.0.3 on 2026-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_remove_store_close_time_remove_store_open_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='handling_fee',
        ),
        migrations.RemoveField(
            model_name='pendingorder',
            name='handling_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='handling_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='handling_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
