# Generated by Django 6.0.3 on 2026-07-27 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_devicetoken_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'All Customers'), ('new', 'New Customers'), ('repeat', 'Repeat Customers'), ('inactive', 'Inactive Customers'), ('phone', 'Specific Customer')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('high_priority', models.BooleanField(default=False)),
                ('save_history', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('successful', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
