# Generated by Django 6.0.3 on 2026-04-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_remove_store_close_time_remove_store_open_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='handling_fee',
        ),
        migrations.RemoveField(
            model_name='pendingorder',
            name='handling_fee',
        ),
    ]
