# Generated by Django 6.0.3 on 2026-04-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0031_order_handling_fee_pendingorder_handling_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='handling_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='handling_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
