# Generated by Django 6.0.3 on 2026-08-07 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0031_complaint_complaintphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='phone',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('UNDER_REVIEW', 'Under Review'), ('WAITING_RESTAURANT', 'Waiting for Restaurant'), ('WAITING_DELIVERY', 'Waiting for Delivery Partner'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], db_index=True, default='NEW', max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='marketplace.store'),
        ),
    ]
