# Generated by Django 6.0.3 on 2026-08-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0032_alter_complaint_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='customer_note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
