# Generated by Django 6.0.3 on 2026-08-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0033_order_customer_note_pendingorder_customer_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unavailable_afternoon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unavailable_evening',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unavailable_morning',
        ),
        migrations.AddField(
            model_name='product',
            name='unavailable_10_12',
            field=models.BooleanField(default=False, help_text='Hide product from 10 AM - 12 PM'),
        ),
        migrations.AddField(
            model_name='product',
            name='unavailable_12_3',
            field=models.BooleanField(default=False, help_text='Hide product from 12 PM - 3 PM'),
        ),
        migrations.AddField(
            model_name='product',
            name='unavailable_3_630',
            field=models.BooleanField(default=False, help_text='Hide product from 3 PM - 6:30 PM'),
        ),
        migrations.AddField(
            model_name='product',
            name='unavailable_630_9',
            field=models.BooleanField(default=False, help_text='Hide product from 6:30 PM - 9 PM'),
        ),
    ]
