# Generated by Django 6.0.3 on 2026-08-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0035_customer_customerotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerotp',
            name='otp',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='otp',
            field=models.CharField(max_length=128),
        ),
    ]
