# Generated by Django 6.0.3 on 2026-08-30 12:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0036_alter_customerotp_otp_alter_pendingorder_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='payment_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='payment_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
