# Generated by Django 6.0.3 on 2026-08-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0037_pendingorder_payment_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingorder',
            name='payment_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
