# Generated by Django 6.0.3 on 2026-08-30 22:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0038_alter_pendingorder_payment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingorder',
            name='payment_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
