# Generated by Django 6.0.3 on 2026-09-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0040_customer_date_of_birth_customer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_orders', to='marketplace.customer')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_record', to='marketplace.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
