# Generated by Django 6.0.3 on 2026-09-14 11:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0042_lokamoneyaccount_lokamoneytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CustomerReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20, unique=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=10)),
                ('is_rewarded', models.BooleanField(default=False)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_record', to='marketplace.customer')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='marketplace.customer')),
            ],
        ),
    ]
