# Generated by Django 6.0.3 on 2026-09-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0043_customer_referral_code_customerreferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loka_money_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='loka_money_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
