# Generated by Django 6.0.3 on 2026-09-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0046_partnerdevicetoken_storepartnerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='partner_unavailable',
            field=models.BooleanField(default=False, help_text='Temporarily unavailable by store partner'),
        ),
    ]
