# Generated by Django 6.0.3 on 2026-09-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0047_product_partner_unavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='partner_closed',
            field=models.BooleanField(default=False, help_text='Temporarily closed by store partner'),
        ),
    ]
