# Generated by Django 6.0.3 on 2026-10-01 11:24

from django.db import migrations, models


def populate_order_commission_percent(apps, schema_editor):
    Order = apps.get_model("marketplace", "Order")

    db_alias = schema_editor.connection.alias

    orders = (
        Order.objects
        .using(db_alias)
        .select_related("store")
    )

    for order in orders.iterator():
        order.commission_percent = order.store.commission_percent or 0
        order.save(
            update_fields=["commission_percent"],
            using=db_alias
        )


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0048_store_partner_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_percent',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Commission percentage applicable when this order was placed',
                max_digits=5
            ),
        ),

        migrations.AddField(
            model_name='pendingorder',
            name='commission_percent',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Commission percentage applicable when this pending order was created',
                max_digits=5
            ),
        ),

        migrations.RunPython(
            populate_order_commission_percent,
            migrations.RunPython.noop,
        ),
    ]